{ config, pkgs, ... }:

{
  imports =
    [ ./hardware-configuration.nix
    ];

  # Use the systemd-boot EFI boot loader.
  boot.loader = {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
  };

  # Networking setup
  networking.hostName = "thinkpad"; # Define your hostname.
  networking.networkmanager = {
    enable = true;    
  };

  # Currently, I live in US/Eastern
  time.timeZone = "US/Eastern";

  # Use DHCP for ethernet and wireless interfaces
  networking.useDHCP = false;
  networking.interfaces = {
    enp0s25 = {
       useDHCP = true;
    };
    wlp3s0 = {
      useDHCP = true;
    };
  };
 
  networking.networkmanager.enable = true;

  # Internationalization
  i18n.defaultLocale = "en_US.UTF-8";
  console = {
    font = "Lat2-Terminus16";
    keyMap = "us";
  };

  # Make sound work
  sound.enable = true;
  hardware.pulseaudio.enable = true;

  # Myself
  users.users = {
    samuel = {
      isNormalUser = true;
      extraGroups = [ "wheel" "networkmanager" ];
    };
    samantha = {
      isNormalUser = true;
      extraGroups = [ "wheel" "networkmanager" ];
    };
  };

  # Global packages
  environment.systemPackages = with pkgs; [
    vim # ALWAYS KEEP AN EDITOR!
    curl
    w3m
    git
    fzf
    ripgrep
    firefox
    neofetch
    thefuck
    gcc
    xclip
  ];

  # This is for when I disable i3. The terminal runs a lot more quickly
  # sometimes and I only really want the window manager if I'm doing a lot of
  # browsing.
  programs.tmux = {
    enable = true;
    shortcut = "a";
    clock24 = true;
    escapeTime = 0;
    aggressiveResize = true;
    newSession = true;
    baseIndex = 1;
    extraConfig = ''
      bind | split-window -h -c "#{pane_current_path}"
      bind - split-window -v -c "#{pane_current_path}"
      bind c new-window -c "#{pane_current_path}"
    '';
  };

  # Use the i3 X11 window manager
  services.xserver = {
    enable = false; # Toggle to turn on and off the graphical environment
    
    desktopManager = {
      xterm.enable = false;
    };
  
    displayManager = {
      defaultSession = "none+i3";
    };

    windowManager.i3 = { 
      enable = true;
      extraPackages = with pkgs; [
        dmenu
        i3status
        i3lock
      ];
    };

    # If we don't do this, some inputs fail. I guess this is an alternative
    # to synaptics, whatever that is.
    libinput = {
      enable = true;
      mouse = {
        accelProfile = "flat";
      };
      touchpad = {
        accelProfile = "flat";
	tapping = true;
	middleEmulation = true;
	naturalScrolling = true;
      };
    };
  };

  # Open ports in the firewall.
  networking.firewall.allowedTCPPorts = [ ];
  networking.firewall.allowedUDPPorts = [ ];

  # AUTOGENERATED within =s, tread carefully
  # ========================================================================
  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  # ========================================================================
  system.stateVersion = "21.11"; # Did you read the comment?
}

